name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  builds_docker_image_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - run: docker build . -t girishvg7/next-js-app:latest
      - run: docker push girishvg7/next-js-app:latest
